#!/bin/sh

cat <<EOF
Access-Control-Allow-Origin: *
Content-type: application/json

EOF
exec gluon-neighbour-info -d ::1 -p 1001 -t 1 -c 1 -r nodeinfo | sed 's/"owner":{"contact":"[^"]*"},/"owner":{"contact":"Bitte schreibe eine Mail an technik@freifunk-aachen.de, wenn du Kontakt zu diesem Knotenbetreiber aufnehmen möchtest!"},/'
